[package]
name = "babynotes-seed-gen"
version = "0.1.0"
authors = ["Sirui <msrlancern@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.1"
clap = "2.33.3"
fuzzer = { path = "../fuzzer" }
